services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:17
    ports:
      - "127.0.0.1:18432:5432"
    shm_size: 128mb
    environment:
      - 'POSTGRES_DB=brian-bunn'
      - 'POSTGRES_PASSWORD=mibReklcHuHe62BablBr'
      - 'PGDATA=/pgdata'
    volumes:
      - data:/pgdata

volumes:
  data:
  node_modules:
